export const ValidationErrorCode = {
  UNSUPPORTED_VERSION: 'UNSUPPORTED_VERSION',
  NO_MUR: 'NO_MUR',
  NO_PLANCHER_BAS: 'NO_PLANCHER_BAS',
  NO_PLANCHER_HAUT: 'NO_PLANCHER_HAUT',
  NO_BAIE_VITREE: 'NO_BAIE_VITREE',
  NO_PORTE: 'NO_PORTE',
  NO_VENTILATION: 'NO_VENTILATION',
  EMPTY_MUR: 'EMPTY_MUR',
  EMPTY_PLANCHER_BAS: 'EMPTY_PLANCHER_BAS',
  EMPTY_PLANCHER_HAUT: 'EMPTY_PLANCHER_HAUT',
  EMPTY_BAIE_VITREE: 'EMPTY_BAIE_VITREE',
  EMPTY_PORTE: 'EMPTY_PORTE',
  EMPTY_VENTILATION: 'EMPTY_VENTILATION'
};

export const ValidationErrorLevel = {
  FATAL: 'FATAL',
  ERROR: 'ERROR',
  WARNING: 'WARNING'
};
